linkWorkspacePackages: true
packageImportMethod: "clone-or-copy"
cleanupUnusedCatalogs: true
injectWorkspacePackages: true

packages:
  - apps/*
  - packages/*

packageExtensions:
  '@testing-library/jest-dom':
    peerDependencies:
      vitest: '*'
