linkWorkspacePackages: true
packageImportMethod: "clone-or-copy"
cleanupUnusedCatalogs: false
injectWorkspacePackages: true

packages:
  - apps/*
  - packages/*

packageExtensions:
  '@testing-library/jest-dom':
    peerDependencies:
      vitest: '*'

catalog:
  '@azure/identity': ^4.11.2
