@startuml Sequence GET CdC vouchers list
participant "Citizen" as cit
participant "CdC Backend Functions" as be
participant "Redis" as redis
participant "Sogei" as sogei

cit -> be: List created CdC vouchers
activate be
be -> redis: Check session
alt Session found
    be <-> sogei: Get CdC vouchers
    be -> cit: 200 CdC vouchers list
else Session not found
    be -> cit: 401 Unauthorized
end
deactivate be

@enduml