openapi: 3.0.0
info:
  title: Liberty REST APIs
  description: Discover REST APIs available within Liberty
  version: 1.0.0
servers:
- url: https://ssotest.cartadellacultura.it
security:
  - BearerAuth: []
paths:
  /CDCUtenteWS/rest/secured/beneficiario/stato:
    get:
      operationId: getStatoBeneficiario
      description: Get
      responses:
        200:
          description: Default response
  /CDCUtenteWS/rest/secured/beneficiario/versione:
    get:
      operationId: getVersioneBeneficiario
      description: Get
      responses:
        200:
          description: Default response
  /CDCUtenteWS/rest/secured/beneficiario/registrazione:
    post:
      operationId: postRegistrazioneBeneficiario
      description: Post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputBeneficiarioBean'
      responses:
        200:
          description: Default response
  /CDCUtenteWS/rest/unsecured/versione:
    get:
      operationId: getVersione
      description: Get
      responses:
        200:
          description: Default response
          content:
            text/plain: {}
components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    EsercenteBuonoBean:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        tipo:
          type: string
    VoucherGeneratorOutputBean:
      type: object
      properties:
        codErrore:
          type: string
        descrErrore:
          type: string
        status:
          type: string
          enum:
          - NO_INPUT
          - ANNI_RIFERIMENTO_NON_FORNITI
          - LISTA_ANNI_VUOTA
          - FORMATO_ANNI_ERRATO
          - INPUT_SUPERIORE_AL_CONSENTITO
        valore:
          type: number
        stato:
          type: string
        dataCreazione:
          type: string
          format: date-time
        dataSpesa:
          type: string
          format: date-time
        codice:
          type: string
        annoCarta:
          type: string
        esercente:
          $ref: '#/components/schemas/EsercenteBuonoBean'
        qrCode:
          $ref: '#/components/schemas/MimeBean'
        barCode:
          $ref: '#/components/schemas/MimeBean'
    MimeBean:
      type: object
      properties:
        mime_type:
          type: string
        content:
          type: string
    SimpleResponseBean:
      type: object
      properties:
        codErrore:
          type: string
        descrErrore:
          type: string
        status:
          type: string
          enum:
          - NO_INPUT
          - ANNI_RIFERIMENTO_NON_FORNITI
          - LISTA_ANNI_VUOTA
          - FORMATO_ANNI_ERRATO
          - INPUT_SUPERIORE_AL_CONSENTITO
    InputBeneficiarioBean:
      type: object
      properties:
        anniRif:
          type: array
          items:
            $ref: '#/components/schemas/AnniBeneficiario'
    AnniBeneficiario:
      type: object
      properties:
        anno:
          type: string