openapi: 3.0.1
info:
  version: 0.0.1
  title: CdC Backend API
  x-logo:
    url: https://io.italia.it/assets/img/io-logo-blue.svg
  description: |
    These APIs serve the microfrontend related to Carta della Cultura
servers:
  - url: /api/v1
security:
  - ApiKeyAuth: []
paths:
  /info:
    get:
      operationId: info
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationInfo"
        "500":
          description: Internal Server error
  /fauth:
    get:
      operationId: fimsAuth
      parameters:
        - in: query
          name: device
          required: false
          schema:
            type: string
      responses:
        "302":
          description: Redirect to openid provider
        "500":
          description: Internal Server error
  /fcb:
    get:
      operationId: fimsCallback
      parameters:
        - in: query
          name: state
          required: true
          schema:
            type: string
        - in: query
          name: code
          required: true
          schema:
            type: string
        - in: query
          name: iss
          schema:
            type: string
        - in: header
          name: signature
          schema:
            type: string
        - in: header
          name: signature-input
          schema:
            type: string
      responses:
        "302":
          description: Redirect to RP Authorize
        "401":
          description: Unauthorized
        "500":
          description: Internal Server error
  /authorize:
    get:
      operationId: authorize
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Session Token successfully retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionToken"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server error
  /years:
    get:
      operationId: getYears
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Years"
        "500":
          description: Internal Server error
  /card-requests:
    get:
      operationId: getCardRequests
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardRequests"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server error
    post:
      operationId: insertCardRequest
      parameters:
        - in: header
          name: token
          required: true
          schema:
            type: string
      requestBody:
        description: Years to request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/YearsToRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CardRequests"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server error
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Functions-Key
  schemas:
    YearsToRequest:
      type: array
      items:
        type: string
    InternalServerError:
      description: InternalServerError
      allOf:
        - $ref: "#/components/schemas/ProblemJson"
        - type: object
          properties:
            status:
              type: integer
              enum:
                - 500
              example: 500
              description: >-
                The HTTP status code generated by the origin server for this
                occurrence of the problem.
          required:
            - status
    BadRequest:
      description: Bad Request
      allOf:
        - $ref: "#/components/schemas/ProblemJson"
        - type: object
          properties:
            status:
              type: integer
              enum:
                - 400
              example: 400
              description: >-
                The HTTP status code generated by the origin server for this
                occurrence of the problem.
          required:
            - status
    Unauthorized:
      description: Unauthorized
      allOf:
        - $ref: "#/components/schemas/ProblemJson"
        - type: object
          properties:
            status:
              type: integer
              enum:
                - 401
              example: 401
              description: >-
                The HTTP status code generated by the origin server for this
                occurrence of the problem.
          required:
            - status
    ApplicationInfo:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
      required:
        - name
        - version
    SessionToken:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    Years:
      type: array
      items:
        type: string
    CardRequests:
      type: array
      items:
        $ref: "#/components/schemas/CardRequest"
    CardRequest:
      type: object
      properties:
        year:
          type: string
      required:
        - year
    ProblemJson:
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |-
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: about:blank
          example: https://example.com/problem/constraint-violation
        title:
          type: string
          description: >-
            A short, summary of the problem type. Written in english and
            readable

            for engineers (usually not suited for non technical stakeholders and

            not localized); example: Service Unavailable
        status:
          type: integer
          format: int32
          description: >-
            The HTTP status code generated by the origin server for this
            occurrence of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 200
        detail:
          type: string
          description: |-
            A human readable explanation specific to this occurrence of the
            problem.
          example: There was an error processing the request
