@startuml Sequence FIMS auth
participant "App IO" as io
participant "in-app Browser" as iab
participant "CdC Backend Functions" as be
participant "Redis" as redis

activate io
io -> iab: /authorize con session id
deactivate io
activate iab
iab -> be: /api/v1/authorize con session id
activate be
be -> redis: recupera session token
be -> redis: elimina session id
be -> iab: session token
deactivate be

@enduml