openapi: 3.0.0
info:
  title: Carta della Cultura Status APIs
  description: These APIs App IO to known citizen status about Carta della Cultura.
  version: 1.0.0
servers:
- url: https://ssotest.cartadellacultura.it/cdc/v1
tags:
- name: secured
  description: Citizen facing APIs
security:
  - JwtAuth: []
paths:
  /status:
    get:
      tags:
      - secured
      summary: Get the citizen's status about the Carta della Cultura
      operationId: getStatus
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CitizenStatus"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    JwtAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    CitizenStatus:
      type: object
      properties:
        number_of_cards:
          type: integer
          description: The number of active Carta della Cultura cards
          example: 2
        expiration_date:
          type: string
          format: date-time
          description: The expiration date of the Carta della Cultura
          example: "2026-12-31T23:59:59Z"
      required:
        - number_of_cards
        - expiration_date