openapi: 3.0.0
info:
  title: Liberty REST APIs by Sogei
  description: Discover REST APIs available within Liberty
  version: 1.0.0
servers:
- url: https://ssotest.cartadellacultura.it
tags:
- name: /secured/utente
  description: metodi inerenti all'utente
paths:
  /CDCUtenteWS/rest/secured/beneficiario/stato:
    get:
      tags:
      - /secured/utente
      summary: controllo anno registrazione per il beneficiario
      operationId: stato
      security:
        - JwtAuth: []
      responses:
        "200":
          description: Tutto OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListaRegistratoBean'
        "400":
          description: Validazioni non superate
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemBean'
        "401":
          description: Utente non autorizzato
        "403":
          description: Utente non loggato
        "500":
          description: Errore interno.
components:
  securitySchemes:
    JwtAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    ListaRegistratoBean:
      type: object
      properties:
        listaStatoPerAnno:
          type: array
          items:
            $ref: '#/components/schemas/RegistratoBean'
    RegistratoBean:
      type: object
      properties:
        statoBeneficiario:
          type: string
        annoRiferimento:
          type: string
    ProblemBean:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: string
          enum:
          - NO_INPUT
          - ANNI_RIFERIMENTO_NON_FORNITI
          - LISTA_ANNI_VUOTA
          - FORMATO_ANNI_ERRATO
          - INPUT_SUPERIORE_AL_CONSENTITO
        detail:
          type: string
        instance:
          type: string
        errorCode:
          type: string