name: PR Infrastructure Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/**"
      - ".github/workflows/pr_infra.yaml"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@dbc5a5a25c47432b9faca8b183f26d7df707a29b
    name: Code Review Infrastructure Plan
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      override_github_environment: infra-prod
